-- MySQL Script generated by MySQL Workbench
-- Sat Oct  9 12:20:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo` ;

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`account` ;

CREATE TABLE IF NOT EXISTS `demo`.`account` (
  `account_id` BIGINT NOT NULL AUTO_INCREMENT,
  `balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `primary_owner_id` BIGINT NULL DEFAULT NULL,
  `secondary_owner_id` BIGINT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`checking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`checking` ;

CREATE TABLE IF NOT EXISTS `demo`.`checking` (
  `creation_date` DATE NULL DEFAULT NULL,
  `minimum_balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `minimum_balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `monthly_maintenance_fee_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `monthly_maintenance_fee_currency` VARCHAR(255) NULL DEFAULT NULL,
  `penalty_fee_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_fee_currency` VARCHAR(255) NULL DEFAULT NULL,
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK4pww71v1myyn2iai6qm84t29o`
    FOREIGN KEY (`id`)
    REFERENCES `demo`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`credit_card` ;

CREATE TABLE IF NOT EXISTS `demo`.`credit_card` (
  `amount_credit_limit` DECIMAL(19,2) NULL DEFAULT NULL,
  `currency_credit_limit` VARCHAR(255) NULL DEFAULT NULL,
  `amount_interest_rate` DECIMAL(19,2) NULL DEFAULT NULL,
  `currency_interest_rate` VARCHAR(255) NULL DEFAULT NULL,
  `amount_penalty_fee` DECIMAL(19,2) NULL DEFAULT NULL,
  `currency_penalty_fee` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK5nn2ykrc28pst4v0axopldeqv`
    FOREIGN KEY (`id`)
    REFERENCES `demo`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`savings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`savings` ;

CREATE TABLE IF NOT EXISTS `demo`.`savings` (
  `creation_date` DATE NULL DEFAULT NULL,
  `amount_interest_rate` DECIMAL(19,2) NULL DEFAULT NULL,
  `currency_interest_rate` VARCHAR(255) NULL DEFAULT NULL,
  `minimum_balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `minimum_balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `penalty_fee_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_fee_currency` VARCHAR(255) NULL DEFAULT NULL,
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKs02t0s57xrunyqosm96vrttin`
    FOREIGN KEY (`id`)
    REFERENCES `demo`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`student_checking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`student_checking` ;

CREATE TABLE IF NOT EXISTS `demo`.`student_checking` (
  `creation_date` DATE NULL DEFAULT NULL,
  `penalty_fee_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_fee_currency` VARCHAR(255) NULL DEFAULT NULL,
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKcw2ja1qwe1e6xhuj4e1o9jvy6`
    FOREIGN KEY (`id`)
    REFERENCES `demo`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`transaction` ;

CREATE TABLE IF NOT EXISTS `demo`.`transaction` (
  `transaction_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `amount_quantity` DECIMAL(19,2) NULL DEFAULT NULL,
  `currency_quantity` VARCHAR(255) NULL DEFAULT NULL,
  `receiving_account` BIGINT NULL DEFAULT NULL,
  `sending_account` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `FKhv25xm8wisu38pck2asxnshc4` (`receiving_account` ASC) VISIBLE,
  INDEX `FKs853j3lqy4iuo7tovx74a739w` (`sending_account` ASC) VISIBLE,
  CONSTRAINT `FKhv25xm8wisu38pck2asxnshc4`
    FOREIGN KEY (`receiving_account`)
    REFERENCES `demo`.`account` (`account_id`),
  CONSTRAINT `FKs853j3lqy4iuo7tovx74a739w`
    FOREIGN KEY (`sending_account`)
    REFERENCES `demo`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
